function r = init(r,varargin)
% AE 2008-09-03

% randomized are: barColor, dx, trajectoryAngle
r.conditions = struct('isFlashTrial',{},'isMovingTrial',{}, ...
    'flashLocation',{}, 'barColor',{},'trajectoryAngle',{}, ...
    'direction',{},'dx',{});
for i = 1:size(r.barColor,2)
    for j = 1:size(r.trajectoryAngle,2);
        
        % flashes
        nLocs = r.numFlashLocs;
        r.conditions(end+(1:nLocs)) = ...
            struct('isFlashTrial',1, ...
                   'isMovingTrial',0, ...
                   'flashLocation',mat2cell(1:nLocs,1,ones(1,nLocs)), ...
                   'barColor',r.barColor(:,i), ...
                   'trajectoryAngle',r.trajectoryAngle(j), ...
                   'direction',NaN, ...
                   'dx',NaN);
               
        % moving bars
        for k = 1:size(r.dx,2)
            for l = 1:size(r.direction,2)
                r.conditions(end+1) = ...
                    struct('isFlashTrial',0, ...
                           'isMovingTrial',1, ...
                           'flashLocation',NaN, ...
                           'barColor',r.barColor(:,i), ...
                           'trajectoryAngle',r.trajectoryAngle(j), ...
                           'direction',r.direction(l), ...
                           'dx',r.dx(k));
            end
        end
    end
end

% initialize BlockRandomization on condition indices. Since we do not use
% all combinations of parameter sets we can't directly use the block
% randomization
params = struct('conds',1:length(r.conditions));
r.block = init(BlockRandomization,params);
