function assertCorrectParams(e)
% Make sure the necessary parameters are passed.
% AE 2007-10-05

% the following parameters must be set
needed = {'subject', ...
          'bgColor', ...
          'fixSpotColor', ...
          'rewardProb'};
      
% make sure parameters are set
there = cat(1,fieldnames(e.params.constants), ...
              fieldnames(e.params.conditions), ...
              fieldnames(e.params.trials));
missing = ~ismember(needed,there);
if any(missing)
    error('TrialBasedExperiment:assertCorrectParams', ...
          'The following parameters must be set for TrialBasedExperiment:%s', ...
          sprintf('\n%s',needed{missing}));
end
