function [types,sites] = getEventTypes(e)
% Return names and triggering sites of all events for this experiment.
% AE 2007-10-05

types = {'startTrial'; ...
         'showFixSpot'; ...
         'acquireFixation'; ...
         'showStimulus'; ...
         'response'; ...
         'startReward'; ...
         'endReward'; ...
         'eyeAbort'; ...
         'leverAbort'; ...
         'prematureAbort'; ...
         'clearScreen'};

% Site that triggers the above events (0 = Mac/Matlab; 1 = PC/LabView)
sites = [0 0 1 0 1 1 1 1 1 1 0];
