function r = computeConditions(r,params)
% Compute condition pool.
% AE 2007-10-05

nExceptions = length(params.exceptionTypes);
nLocations = length(params.exceptionLocations);

r.conditions = struct('isInitMapping',true, ...
                      'isNormal',false, ...
                      'exceptionType',NaN, ...
                      'exceptionLocation',NaN, ...
                      'direction',NaN);
                  
r.conditions(2) = struct('isInitMapping',false, ...
                         'isNormal',true, ...
                         'exceptionType',NaN, ...
                         'exceptionLocation',NaN, ...
                         'direction',0);

r.conditions(3) = struct('isInitMapping',false, ...
                         'isNormal',true, ...
                         'exceptionType',NaN, ...
                         'exceptionLocation',NaN, ...
                         'direction',1);

for i = 1:nExceptions
    for j = 1:nLocations
        cond = 2 * nLocations * (i-1) + 2 * (j-1) + 3;
        r.conditions(cond+1) = struct('isInitMapping',false, ...
                                      'isNormal',false, ...
                                      'exceptionType',params.exceptionTypes{i}, ...
                                      'exceptionLocation',params.exceptionLocations(j), ...
                                      'direction',0);
        r.conditions(cond+2) = struct('isInitMapping',false, ...
                                      'isNormal',false, ...
                                      'exceptionType',params.exceptionTypes{i}, ...
                                      'exceptionLocation',params.exceptionLocations(j), ...
                                      'direction',1);
    end
end
