function r = computeConditions(r)
% Compute condition pool.
% AE 2007-10-05

r.conditions = struct('trialIndex',{}, ...
                      'blockSize',{}, ...
                      'blockType',{}, ...
                      'trialType',{});

% 1 trial regular block
r.conditions(end+1) = struct('trialIndex',1, ...
                             'blockSize',1, ...
                             'blockType',ReportPerceptRandomization.REGULAR_BLOCK, ...
                             'trialType',ReportPerceptRandomization.REGULAR_REWARD);
                  
for i = 2:r.maxBlockSize
    
    % regular blocks
    for j = 1:i-1
        r.conditions(end+1) = struct('trialIndex',j, ...
                                     'blockSize',i, ...
                                     'blockType',ReportPerceptRandomization.REGULAR_BLOCK, ...
                                     'trialType',ReportPerceptRandomization.REGULAR_NO_REWARD);
    end
    
    % last trial in regular block (here the monkey gets rewarded)
    r.conditions(end+1) = struct('trialIndex',i, ...
                                 'blockSize',i, ...
                                 'blockType',ReportPerceptRandomization.REGULAR_BLOCK, ...
                                 'trialType',ReportPerceptRandomization.REGULAR_REWARD);

    % probe blocks
    for j = 1:i-1
        r.conditions(end+1) = struct('trialIndex',j, ...
                                     'blockSize',i, ...
                                     'blockType',ReportPerceptRandomization.PROBE_BLOCK, ...
                                     'trialType',ReportPerceptRandomization.REGULAR_NO_REWARD);
        r.conditions(end+1) = struct('trialIndex',j, ...
                                     'blockSize',i, ...
                                     'blockType',ReportPerceptRandomization.PROBE_BLOCK, ...
                                     'trialType',ReportPerceptRandomization.PROBE);
    end

    % last trial in probe block (here the monkey gets rewarded)
    r.conditions(end+1) = struct('trialIndex',i, ...
                                 'blockSize',i, ...
                                 'blockType',ReportPerceptRandomization.PROBE_BLOCK, ...
                                 'trialType',ReportPerceptRandomization.REGULAR_REWARD);
end
